### PR TITLE
fix issue with connecting to Google Talk service

### PR DESCRIPTION
**Pull request by vogel**
My Google Talk account is vogel@kadu.im
It used domain kadu.im but conencts to host talk.google.com (custom
host/port settings).

When I try to connect with setIgnoreSslErrors(false) I get
QAbstractSocket::SslHandshakeFailedError error. This fixes that issue.

### CODE REVIEW

**Comment by jlaine** [comment]
Also could you please answer the question I asked by email: why are you forcing the host name? The nominal way to connect is to do DNS SRV lookups based on the JID domain.

**Comment by vogel** [comment]
I've not received any questions by e-mail. Maybe it got into spam folder or I just missed the e-mail.

And you are right - the forcing is not needed. It was in my configuration for several years (I'm not the first XMPP developer for Kadu, so there is a lot of cargo programming).

**Comment by vogel** [comment]
So that mean I will just have to add option to setIgnoreSslErrors(true) if certificate does not match. I would much more prefer to use setCaCertificates() and to allow users to accept certificates, but I do not see how I could get non-verified certificate from error() signal of QXmppClient.

**Comment by vogel** [comment]
I'll find another way.

**Pull request closed without merging**
