### PR TITLE
FileSharingManager: Apply 'clang-format'

### PR DESCRIPTION
**Pull request by melvo**
PR check list:
- [x] Document your code
- [x] Add `\since QXmpp 1.X`, `QXMPP_EXPORT`
- [x] Fix doxygen warnings (see log when building with `-DBUILD_DOCUMENTATION=ON`)
- [x] Update `doc/doap.xml`
- [x] Add unit tests
- [x] Format the code: Run `clang-format -i src/<edited-file(s)> tests/<edited-file(s)>`

### CODE REVIEW

**Comment by JBBgameich** [comment]
I don't get any changes when running `clang-format-15 -i src/client/QXmppFileSharingManager.cpp` on master. Which version of clang-format are you using?

**Comment by melvo** [comment]
> I don't get any changes when running `clang-format-15 -i src/client/QXmppFileSharingManager.cpp` on master. Which version of clang-format are you using?

I used `clang-format` 14.

**Comment by lnjX** [comment]
This looks wrong. And in general, you only have to format your personal changes, not the whole project. I can format the whole project when releasing or once a year, so we don't get too much noise from me forgetting to run clang format. A CI check for PRs could also be helpful.

**Comment by melvo** [comment]
> A CI check for PRs could also be helpful.

I opened #491 for that purpose.

**Comment by melvo** [comment]
@lnjX This should be reopened since both https://github.com/qxmpp-project/qxmpp/pull/491/files#diff-e8fbcf424898cae6fc11412c52bbd57a6bd05561b745e4e07134155327fd402d and my now updated local clang-format-15 reformat it that way.

**Comment by lnjX** [comment]
I cannot reopen this (the branch was recreated)

**Comment by melvo** [comment]
It is fixed by 98bfe936e25c462df8e3650a436d9db31b237cd9.

**Pull request closed without merging**
