### PR TITLE
README: Make headings not so offensive (caps lock)

### PR DESCRIPTION
**Pull request by lnjX**
I think this looks better.

### CODE REVIEW

**Comment by jlaine** [comment]
Uh. Seriously? If this is really important to you just go ahead an merge it..

**Comment by lnjX** [comment]
> Uh. Seriously? If this is really important to you just go ahead an merge it..

I don't have commit access.

**Comment by tehnick** [comment]
This PR cannot be merget as is due to conflict with other changes in master branch. I'll resolve this conflict manually.

**Comment by tehnick** [comment]
8cb3bb4a6d51ca26e0c75ea6ef3f9a3449c00f2b

Thanks.

**Pull request closed without merging**
