### PR TITLE
added some probably forgotten promise resolutions

### PR DESCRIPTION
**Pull request by TheBluestBird**
PR check list:
- [x] Document your code
- [x] Add `\since QXmpp 1.X`, `QXMPP_EXPORT`
- [x] Fix doxygen warnings (see log when building with `-DBUILD_DOCUMENTATION=ON`)
- [x] Update `doc/doap.xml`
- [x] Add unit tests
- [x] Format the code: Run `clang-format -i src/<edited-file(s)> tests/<edited-file(s)>`

The changes are insignificant, it doesn't feel like it requires to document them or do some meta work.
But if you'll tell - I'm gonna try to cover that case in unit testing

### CODE REVIEW

**Comment by melvo** [comment]
Thanks! It was introduced by b17284ee7d674416e0d11f1699f73fcc606262d4.
Please write the commit message starting with an upper case letter and the imperative.

**Comment by TheBluestBird** [comment]
This way will do?

**Comment by melvo** [comment]
Yes, thanks!

**Review by lnjX — APPROVED** [review]
Thanks for fixing, i really don't know how this happened.

**Pull request merged**
