### PR TITLE
Implemented XEP-0280: Message Carbons

### PR DESCRIPTION
**Pull request by fbeutel**

### CODE REVIEW

**Comment by fbeutel** [comment]
Any chance of getting this (and possibly #87 ) merged some time soon?
Just let me know if anything is missing...

**Comment by olesalscheider** [comment]
It would be nice to get this merged...

**Comment by jlaine** [comment]
I have merge the pull request, but as an afterthought, QXmppCarbonsManager would be the only manager with a name in plural form (Carbon**s**), maybe singular would be more consistent with the rest of QXmpp. Georg, thoughts?

**Comment by jlaine** [comment]
Another comment : what is the point of the "carbonsEnabled" property of QXmppCarbonsManager, it seems to do nothing?

**Pull request merged**
