### PR TITLE
Add support for NV21 video format in vpx encoder

### PR DESCRIPTION
**Pull request by hhaveri**

### CODE REVIEW

**Comment by jlaine** [comment]
Cool! I'm starting to wonder whether we should break out the format conversion code so that we can add unit tests. Thoughts?

**Comment by hhaveri** [comment]
No thoughts at the moment if you're asking from me :)

**Comment by jlaine** [comment]
This PR contains two unrelated changes, on of which is a breaking API change. Can you please only include the NV12 support in this PR, break it out to a separate function and provide a unit test for it as requested?

**Comment by lnjX** [comment]
I'm closing this due to inactivity and because we probably don't need this anymore as soon as #207 is done.

**Pull request closed without merging**
