### PR TITLE
XEP-0297: Stanza Forwarding

### PR DESCRIPTION
**Pull request by jaragont**
XEP-0297: Stanza Forwarding

### CODE REVIEW

**Comment by jlaine** [comment]
I don't believe this was ever merged. It lacks documentation, and I'm not sure what the point of the QSharedPointer is. Also, is it doesn't seem possible to clear the forwarded message?

**Comment by LNJ2** [comment]
At least there is https://github.com/qxmpp-project/qxmpp/blob/master/src/client/QXmppCarbonManager.h for carbons.

**Comment by olesalscheider** [comment]
It accesses the forwarded dom element internally and just returns the forwarded message.
In contrast, this PR exposes XEP-0297 to the user.

**Comment by jlaine** [comment]
OK, I'm not sure there is any value in exposing XEP-0297 directly since we already have a higher-level manager, so I'm going to close this.

**Pull request closed without merging**
