### PR TITLE
Support to build both static and shared library

### PR DESCRIPTION
**Pull request by LightZam**
* add BUILD_SHARED to support library type
* add BUILD_SHARED to README
* add default value hint to README

### CODE REVIEW

**Comment by LightZam** [comment]
@jlaine 
this is to support user have ability to build both static and shared library
what do you think about it?

**Comment by olesalscheider** [comment]
LGTM

**Comment by tehnick** [comment]
I would vote for adding of `BUILD_STATIC` configuration option in addition to `BUILD_SHARED` one. Many projects allow to build static and shared libraries simultaneously. For example: freeglut, libpng, proj, SDL2, etc..

All projects listed above had been using autotools in the past, but are using cmake build system now. I have remembered them because I have used them to test cross-compilation for MS Windows, GNU/Linux and Android in my CI system ([sibuserv](https://github.com/sibuserv)).

**Comment by tehnick** [comment]
More examples from [MXE project](https://mxe.cc/) for packages with cmake based projects:
```
$ grep -r 'CMAKE_.*_BOOL' src/*.mk
src/alure.mk:        -DDYNLOAD=$(CMAKE_SHARED_BOOL) \
src/alure.mk:        -DBUILD_SHARED=$(CMAKE_SHARED_BOOL) \
src/alure.mk:        -DBUILD_STATIC=$(CMAKE_STATIC_BOOL) \
src/box2d.mk:        -DBOX2D_BUILD_STATIC=$(CMAKE_STATIC_BOOL) \
src/box2d.mk:        -DBOX2D_BUILD_SHARED=$(CMAKE_SHARED_BOOL) \
src/cegui.mk:# freeimage and xerces don't have shared builds - disable with $(CMAKE_STATIC_BOOL)
src/cegui.mk:        -DCEGUI_BUILD_SHARED_CONFIGURATION=$(CMAKE_SHARED_BOOL) \
src/cegui.mk:        -DCEGUI_BUILD_STATIC_CONFIGURATION=$(CMAKE_STATIC_BOOL) \
src/cegui.mk:        -DCEGUI_BUILD_STATIC_FACTORY_MODULE=$(CMAKE_STATIC_BOOL) \
src/cegui.mk:        -DCEGUI_BUILD_XMLPARSER_XERCES=$(CMAKE_STATIC_BOOL) \
src/cegui.mk:        -DCEGUI_BUILD_IMAGECODEC_FREEIMAGE=$(CMAKE_STATIC_BOOL) \
src/cgal.mk:        -DCGAL_Boost_USE_STATIC_LIBS:BOOL=$(CMAKE_STATIC_BOOL) \
src/chipmunk.mk:        -DINSTALL_STATIC=$(CMAKE_STATIC_BOOL)
src/cmake-conf.mk:        -DCMAKE_SHARED_BOOL=$(CMAKE_SHARED_BOOL) \
src/cmake-conf.mk:        -DCMAKE_STATIC_BOOL=$(CMAKE_STATIC_BOOL) \
src/freeglut.mk:        -DFREEGLUT_BUILD_STATIC_LIBS=$(CMAKE_STATIC_BOOL) \
src/freeglut.mk:        -DFREEGLUT_BUILD_SHARED_LIBS=$(CMAKE_SHARED_BOOL)
src/intel-tbb.mk:        -DTBB_BUILD_SHARED=$(CMAKE_SHARED_BOOL) \
src/intel-tbb.mk:        -DTBB_BUILD_STATIC=$(CMAKE_STATIC_BOOL) \
src/itpp.mk:        -DITPP_SHARED_LIB=$(CMAKE_SHARED_BOOL) \
src/jasper.mk:        -DJAS_ENABLE_SHARED=$(CMAKE_SHARED_BOOL) \
src/libftdi1.mk:        -DSHAREDLIBS=$(CMAKE_SHARED_BOOL) \
src/libftdi1.mk:        -DSTATICLIBS=$(CMAKE_STATIC_BOOL) \
src/libharu.mk:        -DLIBHPDF_SHARED=$(CMAKE_SHARED_BOOL) \
src/libharu.mk:        -DLIBHPDF_STATIC=$(CMAKE_STATIC_BOOL) \
src/libical.mk:        -DSTATIC_ONLY=$(CMAKE_STATIC_BOOL) \
src/libical.mk:        -DSHARED_ONLY=$(CMAKE_SHARED_BOOL) \
src/libmysqlclient.mk:        -DDISABLE_SHARED=$(CMAKE_STATIC_BOOL) \
src/libssh.mk:        -DWITH_STATIC_LIB=$(CMAKE_STATIC_BOOL) \
src/libssh.mk:        -DWITH_SHARED_LIB=$(CMAKE_SHARED_BOOL) \
src/libwebsockets.mk:        -DLWS_WITH_STATIC=$(CMAKE_STATIC_BOOL) \
src/libwebsockets.mk:        -DLWS_WITH_SHARED=$(CMAKE_SHARED_BOOL) \
src/metis.mk:        -DSHARED=$(CMAKE_SHARED_BOOL)
src/miniupnpc.mk:        -DUPNPC_BUILD_STATIC=$(CMAKE_STATIC_BOOL) \
src/miniupnpc.mk:        -DUPNPC_BUILD_SHARED=$(CMAKE_SHARED_BOOL) \
src/oce.mk:        -DOCE_BUILD_SHARED_LIB=$(CMAKE_SHARED_BOOL) \
src/openscenegraph.mk:        -DDYNAMIC_OPENTHREADS=$(CMAKE_SHARED_BOOL) \
src/openscenegraph.mk:        -DDYNAMIC_OPENSCENEGRAPH=$(CMAKE_SHARED_BOOL) \
src/openthreads.mk:        -DDYNAMIC_OPENTHREADS=$(CMAKE_SHARED_BOOL) \
src/osgearth.mk:        -DDYNAMIC_OSGEARTH=$(CMAKE_SHARED_BOOL) \
src/pcl.mk:        -DPCL_SHARED_LIBS=$(CMAKE_SHARED_BOOL) \
src/physfs.mk:        -DPHYSFS_BUILD_STATIC=$(CMAKE_STATIC_BOOL) \
src/physfs.mk:        -DPHYSFS_BUILD_SHARED=$(CMAKE_SHARED_BOOL) \
src/polarssl.mk:        -DUSE_STATIC_POLARSSL_LIBRARY=$(CMAKE_STATIC_BOOL) \
src/polarssl.mk:        -DUSE_SHARED_POLARSSL_LIBRARY=$(CMAKE_SHARED_BOOL) \
src/qtkeychain.mk:        -DQTKEYCHAIN_STATIC=$(CMAKE_STATIC_BOOL) \
src/tidy-html5.mk:        -DBUILD_SHARED_LIB=$(CMAKE_SHARED_BOOL)
src/vmime.mk:        -DVMIME_BUILD_STATIC_LIBRARY=$(CMAKE_STATIC_BOOL) \
src/vmime.mk:        -DVMIME_BUILD_SHARED_LIBRARY=$(CMAKE_SHARED_BOOL) \
src/vtk.mk:        -DBUILD_SHARED_LIBS=$(CMAKE_SHARED_BOOL) \
src/x265.mk:        -DENABLE_SHARED=$(CMAKE_SHARED_BOOL) \
src/zstd.mk:        -DZSTD_BUILD_STATIC=$(CMAKE_STATIC_BOOL) \
src/zstd.mk:        -DZSTD_BUILD_SHARED=$(CMAKE_SHARED_BOOL) \
```
Unfortunately, some of packages still use autootols scripts even if projects support builds using cmake. That's why the number of examples above is such small...

**Comment by jlaine** [comment]
@olesalscheider @tehnick what's your opinion on the current state of this PR? As far as I can tell, the new option allows you to *either* build a static *or* a shared (default) library. Is this OK ?

**Comment by olesalscheider** [comment]
Yes, it only allows to build either a static or a shared library with the current patch.
I guess it would be enough for us: I expect that Linux distributions will only ship the shared library and the static library will only be used by people who want to ship an app. But then they don't need the shared one.

On the other hand it is easy to support building both simultaneously. And maybe there are use cases that I do not think of. So why not...

**Comment by jlaine** [comment]
@olesalscheider OK so I think we can merge this PR, release 1.0.0 and see if anyone actually needs the static + shared option. I really like the fact this PR updates the README to state what the defaults are.

**Pull request merged**
