### PR TITLE
Fix build with Qt 5.7

### PR DESCRIPTION
**Pull request by lnjX**
We only test 5.9 with the CI... :/

### CODE REVIEW

**Comment by tehnick** [comment]
Why do you care about Qt 5.7.x?

**Comment by lnjX** [comment]
Officially we still support 5.7 (and I came up with the idea of testing that). We could also just increase our dependency to 5.9.

**Comment by tehnick** [comment]
> Officially we still support 5.7

I see only one possible reason for this: support of MS Windows XP. Which is unsupported by Microsoft since 2014...

> We could also just increase our dependency to 5.9.

+1 for this. Since the next minor version.

Just a reminder... Classical versioning scheme: `<major>.<minor>.<patch>`.

**Comment by tehnick** [comment]
Small reminder 2: we still support Ubuntu 18.04 LTS, where Qt 5.9.x is used:
https://packages.ubuntu.com/bionic/qtbase5-dev
So the minimal requirement to Qt version as 5.9 will not break this.

**Comment by lnjX** [comment]
> I see only one possible reason for this: support of MS Windows XP. Which is unsupported by Microsoft since 2014...
I think that even required 5.6. But I don't think it works with C++17 anyways.

> Just a reminder... Classical versioning scheme: `<major>.<minor>.<patch>`.
What do you mean? (I suggested 5.9 because of Ubuntu Bionic.)

**Comment by tehnick** [comment]
>> We could also just increase our dependency to 5.9.
>
> +1 for this. Since the next minor version.

Please add an issue to not forget this.

**Comment by lnjX** [comment]
I can just increase it on the master branch already

**Comment by tehnick** [comment]
>>  I see only one possible reason for this: support of MS Windows XP. Which is unsupported by Microsoft since 2014...
>
> I think that even required 5.6. But I don't think it works with C++17 anyways.

I still may build `qxmpp` for WinXP using one of snapshots of [MXE project](https://mxe.cc/) with Qt 5.7.1.

> What do you mean?

I mean:
1) save support of Qt 5.7.x in qxmpp 1.4.x
2) bump minimal requirement to Qt 5.9.x since qxmpp 1.5.0 release

**Comment by tehnick** [comment]
WinXP support was broken in Qt only since Qt 5.8.0 if you do not remember.

**Comment by lnjX** [comment]
Alright, I created #340.

**Pull request merged**
